name: Build and Release Electron Vue App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
    types: [ closed ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    environment: app
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      # Adding Vitest test step
      - name: Run Vitest Tests
        run: npm run test
        env:
          NODE_ENV: test

      - name: Build Electron App for macOS
        run: npm run electron:build -- --mac
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          # Adjust the file pattern to match the output for macOS builds
          files: dist_electron/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
